### ISSUE TITLE
.y(

### ISSUE THREAD

**Issue by fjahn** [borgar/textbox#8]
Thank you for this awesome library!

While playing around with the library, I noticed that there is a modifier to offset the text in the x-coordinate.
In my opinion, it would make sense to have a similar modifier for the y-coordinate as well.

Do you plan to maintain this library?

**Comment by fjahn** [comment]
I realized later after studying some of the [demo code](https://observablehq.com/@borgar/textbox-features-demo?collection=@borgar/textbox) that you can modify the position where the text is rendered by calling `ctx.translate` beforehand. Therefore, having a property to offset on the y-coordinate is not necessary.

Still, it is weird that there is a property to offset on x, but not on y.

**Comment by borgar** [comment]
> Do you plan to maintain this library?

Yes, I intend to both keep using it and maintaining it for the foreseeable future.

> Still, it is weird that there is a property to offset on x, but not on y.

Yes, perhaps the parameter would have been better named `.indent` to be more descriptive of what it actually does. I may change that next version. 🙂

**Comment by fjahn** [comment]
I see, so x is intended to be used to have different intendations for individual lines, not to have a margin for the text!

**Comment by borgar** [comment]
> I see, so x is intended to be used to have different intendations for individual lines, not to have a margin for the text!

Yes, I updated the documentation slightly to make that more clear. But ultimately you are exposing that the method was poorly named.
